# Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [5]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5969,6634,-1.611463,0.190648,0.901715,1.531254,-1.535865,0.799245,1.513786,0.495829,0.200390,...,0.211223,0.007477,1.026272,0.057628,-0.024955,-0.368263,0.081684,0.140669,458.92,0.0
5970,6635,-1.420272,1.449354,1.320110,-1.894320,0.913695,0.454601,0.894179,-0.385450,2.433841,...,-0.529027,-0.368394,-0.247773,-1.189156,-0.126040,0.701487,0.277333,-0.222694,0.77,0.0
5971,6637,-1.206696,0.284728,2.152053,-2.850437,-0.437285,-0.238376,-0.333341,0.334679,2.870542,...,0.039460,0.464476,-0.457193,-0.556105,0.517579,0.008006,0.366054,0.185008,14.00,0.0
5972,6644,1.067611,0.091006,-0.153917,0.704233,0.113894,-0.826866,0.567690,-0.464181,0.957295,...,-0.476723,-1.410090,-0.037550,-0.177773,0.321810,0.114930,-0.109640,0.023205,139.90,0.0
5973,6645,-0.535272,-0.132299,2.180041,1.018303,-1.498819,0.529570,0.420147,0.045445,1.543919,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5974 entries, 0 to 5973
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    5974 non-null   int64
 1   V1      5974 non-null   float64
 2   V2      5974 non-null   float64
 3   V3      5974 non-null   float64
 4   V4      5974 non-null   float64
 5   V5      5974 non-null   float64
 6   V6      5974 non-null   float64
 7   V7      5974 non-null   float64
 8   V8      5974 non-null   float64
 9   V9      5974 non-null   float64
 10  V10     5974 non-null   float64
 11  V11     5974 non-null   float64
 12  V12     5974 non-null   float64
 13  V13     5974 non-null   float64
 14  V14     5974 non-null   float64
 15  V15     5974 non-null   float64
 16  V16     5974 non-null   float64
 17  V17     5974 non-null   float64
 18  V18     5973 non-null   float64
 19  V19     5973 non-null   float64
 20  V20     5973 non-null   float64
 21  V21     5973 non-null   float64
 22  V22     5973 non-null   float64
 23  V23     5973 non-null   float64
 24  V24     5973 non-null   float64
 25  V25     5973 non-null   float64
 26  V26     5973 non-null   float64
 27  V27     5973 non-null   float64
 28  V28     5973 non-null   float64
 29  Amount  5973 non-null   float64
 30  Class   5973 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.4 MB

In [8]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    5970
1.0       3
Name: Class, dtype: int64

**This Dataset is highly unblanced**

0 --> Normal Transaction

1 --> fraudulent transaction

In [10]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [11]:
# statistical measures of the data
legit.Amount.describe()

count    5970.000000
mean       64.965707
std       192.429839
min         0.000000
25%         4.450000
50%        15.620000
75%        56.485000
max      7712.430000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count      3.000000
mean     256.310000
std      264.880121
min        0.000000
25%      119.965000
50%      239.930000
75%      384.465000
max      529.000000
Name: Amount, dtype: float64

In [13]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,2677.40201,-0.264965,0.285625,0.844580,0.102656,0.000958,0.195420,0.018542,-0.039195,0.397472,...,0.055426,-0.043268,-0.161540,-0.036683,0.028985,0.089890,-0.040132,0.025238,0.006163,64.965707
1.0,1780.00000,-2.553039,0.184644,-0.293711,2.872264,0.005330,-0.855718,-0.549831,0.308239,-1.093098,...,0.599742,0.294921,-0.177321,0.361160,-0.020311,0.056068,-0.170050,0.015979,-0.086847,256.310000

**Under-Sampling******

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [14]:
legit_sample = legit.sample(n=492)

# Concatenating two DataFrames

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
4211,3751,1.376162,-0.725459,-0.929720,-1.605744,1.445412,3.279439,-1.153078,0.706971,0.358573,...,-0.270210,-0.905140,0.069753,0.920690,0.352242,-0.509772,-0.022394,0.017711,55.00,0.0
3945,3562,0.763766,-0.779865,1.602228,1.346287,-0.896804,1.949052,-1.303501,0.871121,1.462470,...,0.345170,1.180964,0.005787,-0.640357,0.032097,-0.084282,0.146088,0.041346,86.06,0.0
5614,5794,1.163712,0.254078,0.729219,0.708552,-0.280902,-0.273400,-0.223618,-0.000221,1.087735,...,-0.318169,-0.684918,0.193768,0.151510,0.056514,0.056413,-0.044276,0.000501,1.29,0.0
771,581,1.153758,0.132273,0.382969,1.405063,-0.224287,-0.197295,0.020653,0.029260,0.412254,...,-0.107809,-0.125231,-0.057041,0.073082,0.633977,-0.310685,0.033590,0.015250,13.79,0.0
2108,1619,-1.859115,1.255317,0.902888,-1.088329,0.487256,1.392006,0.063104,0.856288,0.404519,...,-0.050317,0.138631,0.114978,-1.019102,-0.515322,0.351324,-0.128524,0.002158,1.00,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5615,5796,-4.861929,-3.463033,0.677789,1.623857,4.422896,2.649519,-1.400165,1.508726,0.384466,...,-0.294286,0.059742,3.281732,0.848990,1.278238,0.013688,0.313144,-0.422099,75.84,0.0
3855,3394,-0.919439,0.101946,2.089027,0.442328,-0.679711,0.390191,-0.219485,0.173832,-1.640113,...,-0.082802,0.324250,0.014165,0.201467,-0.274444,-0.192706,-0.005738,0.114392,58.00,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0

In [18]:
new_dataset['Class'].value_counts()

0.0    492
1.0      3
Name: Class, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,2574.802846,-0.265351,0.217324,0.867257,0.129767,0.045366,0.264017,-0.042066,-0.135082,0.414066,...,0.102184,-0.054382,-0.140550,-0.029062,0.003122,0.098681,-0.063091,0.039786,-0.008208,69.737602
1.0,1780.000000,-2.553039,0.184644,-0.293711,2.872264,0.005330,-0.855718,-0.549831,0.308239,-1.093098,...,0.599742,0.294921,-0.177321,0.361160,-0.020311,0.056068,-0.170050,0.015979,-0.086847,256.310000

# Splitting the data into Features & Targets

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
4211  3751  1.376162 -0.725459 -0.929720 -1.605744  1.445412  3.279439
3945  3562  0.763766 -0.779865  1.602228  1.346287 -0.896804  1.949052
5614  5794  1.163712  0.254078  0.729219  0.708552 -0.280902 -0.273400
771    581  1.153758  0.132273  0.382969  1.405063 -0.224287 -0.197295
2108  1619 -1.859115  1.255317  0.902888 -1.088329  0.487256  1.392006
...    ...       ...       ...       ...       ...       ...       ...
5615  5796 -4.861929 -3.463033  0.677789  1.623857  4.422896  2.649519
3855  3394 -0.919439  0.101946  2.089027  0.442328 -0.679711  0.390191
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920  4462 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788

            V7        V8        V9  ...       V20       V21       V22  \
4211 -1.153078  0.706971  0.358573  ...  0.248607 -0.270210 -0.905140
3945 -1.303501  0.871121  1.462470  ... -0.218696  0.345170  1.180964
5614 -0.223618 -0.000221  1.087735  ... -0.179685 -0.318169 -0.684918
771   0.020653  0.029260  0.412254  ... -0.230877 -0.107809 -0.125231
2108  0.063104  0.856288  0.404519  ...  0.004668 -0.050317  0.138631
...        ...       ...       ...  ...       ...       ...       ...
5615 -1.400165  1.508726  0.384466  ... -0.677948 -0.294286  0.059742
3855 -0.219485  0.173832 -1.640113  ... -0.524191 -0.082802  0.324250
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477
4920  0.562320 -0.399147 -0.238253  ... -0.430022 -0.294166 -0.932391

           V23       V24       V25       V26       V27       V28  Amount
4211  0.069753  0.920690  0.352242 -0.509772 -0.022394  0.017711   55.00
3945  0.005787 -0.640357  0.032097 -0.084282  0.146088  0.041346   86.06
5614  0.193768  0.151510  0.056514  0.056413 -0.044276  0.000501    1.29
771  -0.057041  0.073082  0.633977 -0.310685  0.033590  0.015250   13.79
2108  0.114978 -1.019102 -0.515322  0.351324 -0.128524  0.002158    1.00
...        ...       ...       ...       ...       ...       ...     ...
5615  3.281732  0.848990  1.278238  0.013688  0.313144 -0.422099   75.84
3855  0.014165  0.201467 -0.274444 -0.192706 -0.005738  0.114392   58.00
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00
4920  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93

[495 rows x 30 columns]

In [22]:
print(Y)

4211    0.0
3945    0.0
5614    0.0
771     0.0
2108    0.0
       ...
5615    0.0
3855    0.0
541     1.0
623     1.0
4920    1.0
Name: Class, Length: 495, dtype: float64

# Split the data into Training data & Testing Data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(495, 30) (396, 30) (99, 30)

# Model Training : Logistic Regression

In [25]:
model = LogisticRegression()

In [26]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model evaluation: Accuracy Score

In [27]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [28]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  1.0

In [29]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [30]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9797979797979798